### ISSUE TITLE
Comparison with AirGradient? 

### ISSUE THREAD

**Issue by bnorick** [WesleyE/AirQuality_Monitor#2]
Can you elaborate a bit more (also maybe adding to the README) about how this compares with the Airgradient solution, especially their most recent release?

Looks like many of the same sensors, though I didn't check them all.

**Comment by WesleyE** [comment]
Yep, it's mostly following their reccomondations. However, I wanted full control over the firmware and some add-on capabilities. And I liked the challenge to learn how to build this from scratch.
