### ISSUE TITLE
Who printed the PCB / fulll BOM offering ?

### ISSUE THREAD

**Issue by andygodber** [WesleyE/AirQuality_Monitor#4]
I can see you've given a few suppliers references for the components, wondered if you'd thought about a single supplier solution like PCBWAY?

**Comment by WesleyE** [comment]
Yes I thought about it. However, I also wanted to fiddle with reflowing myself, so I opted for the components and doing it myself.
The SGP41 in particular was hard to source at times, so that would further complicate things.
